export const foodsData = [
  {
    img: "/foodsImages/fruit-1.jpg",
    name: "Juicy Fruit Juice",
    category: "juice",
    shortDesc: "A variety of flavours with high fructose corn...",
    price: 20,
    duration: 30,
  },
  {
    img: "/foodsImages/fruit-2.jpg",
    name: "Juicy Fruit Juice",
    category: "juice",
    shortDesc: "A variety of flavours with high fructose corn...",
    price: 30,
    duration: 15,
  },
  {
    img: "/foodsImages/fruit-3.jpg",
    name: "Juicy Fruit Juice",
    category: "juice",
    shortDesc: "A variety of flavours with high fructose corn...",
    price: 10,
    duration: 45,
  },
  {
    img: "/foodsImages/burger-1.jpg",
    name: "Burgers",
    category: "burger",
    shortDesc: "The Best Classic Burgers in town...",
    price: 40,
    duration: 20,
  },
  {
    img: "/foodsImages/burger-2.jpg",
    name: "Burgers",
    category: "burger",
    shortDesc: "The Best Classic Burgers in town...",
    price: 15,
    duration: 30,
  },
  {
    img: "/foodsImages/burger-grill.jpg",
    name: "Burgers",
    category: "burger",
    shortDesc: "The Best Classic Burgers in town...",
    price: 12,
    duration: 100,
  },
  {
    img: "/foodsImages/chicken-khebab.jpg",
    name: "Spicy Khebabs",
    category: "khebab",
    shortDesc: "Perfect Ghanaian khebab to make your day...",
    price: 250,
    duration: 120,
  },
  {
    img: "/foodsImages/fried-chicken.jpg",
    name: "Spicy Khebabs",
    category: "khebab",
    shortDesc: "Perfect Ghanaian khebab to make your day...",
    price: 10,
    duration: 70,
  },
  {
    img: "/foodsImages/chicken-khebab.jpg",
    name: "Spicy Khebabs",
    category: "khebab",
    shortDesc: "Perfect Ghanaian khebab to make your day...",
    price: 40,
    duration: 90,
  },
  {
    img: "/foodsImages/chicken-fried.jpg",
    name: "Spicy Khebabs",
    category: "khebab",
    shortDesc: "Perfect Ghanaian khebab to make your day...",
    price: 60,
    duration: 30,
  },
  {
    img: "/foodsImages/pizza-boxes.jpg",
    name: "Delicious Pizza",
    category: "pizza",
    shortDesc: "Homemade pizza delivered fresh to your door....",
    price: 10,
    duration: 30,
  },
  {
    img: "/foodsImages/pizza1.jpg",
    name: "Delicious Pizza",
    category: "pizza",
    shortDesc: "Homemade pizza delivered fresh to your door....",
    price: 40,
    duration: 30,
  },
];
